from typing import Any, Protocol


class BrowserClient(Protocol):
    async def goto(self, url: str) -> Any: ...
    async def screenshot(self, path: str | None = None, full_page: bool = False) -> Any: ...
    async def scroll(self, direction: str | None = None) -> Any: ...
    async def click(self, selector: str) -> Any: ...
    async def fill(self, selector: str, text: str) -> Any: ...
    async def extract_text(self, selector: str) -> Any: ...
    async def get_links(self) -> Any: ...
    async def extract_content_smart(self) -> Any: ...
    async def get_news_smart(self, topic: str, max_articles: int) -> Any: ...


async def get_browser() -> BrowserClient: ...
