from typing import Protocol


class TimePlugin(Protocol):
    def get_current_time(self) -> str: ...
    def get_current_date(self) -> str: ...
    def get_day_info(self) -> str: ...
    def format_datetime(self, format_string: str) -> str: ...


def get_time_plugin() -> TimePlugin: ...
