name: typecheck

on:
  pull_request:
  push:

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Run mypy
        run: mypy src/agent/services src/agent/core.py src/agent/server.py --ignore-missing-imports
